context:
  version: "1.3.3"

package:
  name: superfile
  version: ${{ version }}

source:
  url: https://github.com/yorukot/superfile/archive/refs/tags/v${{ version }}.tar.gz
  sha256: f50f4e9c56dff67d3682216950db164fc6caaa1418049c59b42bf5e65d31d04f

build:
  number: 0
  script:
    - if: unix
      then:
        - cd $SRC_DIR
        - go build -o $PREFIX/bin/spf
        - go-licenses save $SRC_DIR --save_path=$RECIPE_DIR/license-files --ignore=github.com/mattn/go-localereader
        - curl -o $RECIPE_DIR/license-files/go-localereader-LICENSE.txt https://raw.githubusercontent.com/mattn/go-localereader/master/LICENSE
    - if: win
      then:
        - go build -o %PREFIX%/spf.exe
        - go-licenses save %SRC_DIR% --save_path=%RECIPE_DIR%/license-files --ignore=github.com/mattn/go-localereader
        - curl -o %RECIPE_DIR%/license-files/go-localereader-LICENSE.txt https://raw.githubusercontent.com/mattn/go-localereader/master/LICENSE


requirements:
  build:
    - ${{ stdlib("c") }}
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - spf --version

about:
  homepage: https://superfile.netlify.app/
  repository: https://github.com/yorukot/superfile
  documentation: https://superfile.netlify.app/getting-started/tutorial/
  summary: Pretty fancy and modern terminal file manager
  description: >
    superfile is a modern terminal file manager crafted with a strong focus on
    user interface, functionality, and ease of use. Built with Go and Bubble
    Tea, it combines a visually appealing design with the simplicity of terminal
    tools, providing a fresh, accessible approach to file management.
  license: MIT
  license_file:
    - LICENSE
    - license-files/

extra:
  recipe-maintainers:
    - apcamargo
    - claudiushaag
